-- show databases;

-- create database CAPSTONE;

-- use CAPSTONE; 

-- show tables;

-- CREATE TABLE USERS (
--    id VARCHAR(30) PRIMARY KEY,
--    name VARCHAR(15) NOT NULL,
--    psword VARCHAR(50) NOT NULL,
--    U_PH_NUM CHAR(13) NULL,
--    U_ADDR TEXT NULL,
-- 	U_CREATE_DATE TIMESTAMP NULL,
-- 	U_CHANGE_DATE TIMESTAMP NULL
-- );

-- CREATE TABLE STORE (
--    S_ID VARCHAR(30) PRIMARY KEY,
--    S_NAME VARCHAR(30) NULL,
--    S_PH_NO CHAR(13) NULL,
--    S_IMAGE TEXT NULL,
--    S_OPENING CHAR(5) NULL,
--    S_DEADLINE CHAR(5) NULL,
--    S_COMMENT TEXT NULL,
--    S_ANNOUNCE TEXT NULL,
--    S_ADDR text NOT NULL,
--    S_REGISTER_DAY timestamp NULL,
--    S_CREATE_DAY timestamp NULL,
--    C_ID VARCHAR(30) NULL, 
--    FOREIGN KEY (C_ID)
--    REFERENCES CEO_USERS (C_ID)
-- );

-- CREATE TABLE CEO_USERS (
--     C_ID VARCHAR(30) PRIMARY KEY,
-- 	C_NAME VARCHAR(30) NOT NULL,
--     C_PSWORD VARCHAR(30) NOT NULL,
--     C_PH_NUM VARCHAR(30) NOT NULL
-- );

-- CREATE TABLE PRODUCT (
-- 	PRODUCT_ID VARCHAR(30) PRIMARY KEY,
--     PRODUCT_NAME VARCHAR(30) NULL,
--     PRODUCT_PRICE INT(10) NULL,
--     PRODUCT_CREATE_DAY timestamp NULL,
--     PRODUCT_CORRECT_DAY timestamp NULL,
--     S_ID VARCHAR(30) NULL,
--     FOREIGN KEY (S_ID)
--     REFERENCES STORE (S_ID)
-- );


-- CREATE TABLE CART (
-- 	CART_ID VARCHAR(30) PRIMARY KEY,
--     id VARCHAR(30) NULL REFERENCES USERS (id),
-- 	PRODUCT_ID VARCHAR(30) NULL REFERENCES PRODUCT (PRODUCT_ID),
-- 	CART_NUM INT(3) DEFAULT 1
    
-- );

-- CREATE TABLE ORDER_LIST (
-- 	O_ID VARCHAR(30) PRIMARY KEY,
-- 	CART_ID VARCHAR(30) NULL REFERENCES CART (CART_ID),
--     O_REQUEST TEXT NULL,
-- 	O_PRICE INT(10) NULL
-- );

-- INSERT INTO store (S_ID,S_NAME,S_ADDR,S_REGISTER_DAY,S_CREATE_DAY)
-- VALUES ('L01','경성사','부산광역시 연제구 배산로 31',NULL,NULL);
-- INSERT INTO STORE_LIST (L_ID,L_NAME,L_ADDR,L_REGISTER_DAY,L_CREATE_DAY)
-- VALUES ('L02','경성종합상사','부산광역시 금정구 동대로 20',NULL,NULL);
-- INSERT INTO STORE_LIST (L_ID,L_NAME,L_ADDR,L_REGISTER_DAY,L_CREATE_DAY)
-- VALUES ('L03','경성퍼크로세탁소','대전광역시 서구 대덕대로 150',NULL,NULL);
-- INSERT INTO STORE_LIST (L_ID,L_NAME,L_ADDR,L_REGISTER_DAY,L_CREATE_DAY)
-- VALUES ('L04','경신세탁','인천광역시 계양구 계양산로 15',NULL,NULL);
-- INSERT INTO STORE_LIST (L_ID,L_NAME,L_ADDR,L_REGISTER_DAY,L_CREATE_DAY)
-- VALUES ('L05','경신세탁소','대구광역시 서구 달구벌대로 361길',NULL,NULL);

-- INSERT INTO store (S_ID, S_NAME, S_PH_NO, S_IMAGE, S_OPENING, S_DEADLINE, S_COMMENT, S_ANNOUNCE, S_ADDR, S_REGISTER_DAY, S_CREATE_DAY, C_ID)
-- VALUES ('1','경성사', '02-111-1111',NULL,NULL,NULL,NULL,NULL,'부산광역시 연제구 배산로 31',NULL,NULL,'admin');
-- INSERT INTO store (S_ID, S_NAME, S_PH_NO, S_IMAGE, S_OPENING, S_DEADLINE, S_COMMENT, S_ANNOUNCE, S_ADDR, S_REGISTER_DAY, S_CREATE_DAY, C_ID)
-- VALUES ('2','경성종합상사', '02-111-1111',NULL,NULL,NULL,NULL,NULL,'부산광역시 금정구 동대로 20',NULL,NULL,'admin1');
-- INSERT INTO store (S_ID, S_NAME, S_PH_NO, S_IMAGE, S_OPENING, S_DEADLINE, S_COMMENT, S_ANNOUNCE, S_ADDR, S_REGISTER_DAY, S_CREATE_DAY, C_ID)
-- VALUES ('3','채연세탁소', '02-111-1011',NULL,NULL,NULL,NULL,NULL,'대구광역시 서구 달구벌대로 361길',NULL,NULL,'admin2');

-- INSERT INTO CEO_USERS (C_ID, C_NAME, C_PSWORD, C_PH_NUM)
-- VALUES ('admin', '임채연', '1234', '010-2242-0064');

-- INSERT INTO CEO_USERS (C_ID, C_NAME, C_PSWORD, C_PH_NUM)
-- VALUES ('admin1', '조승연', '12345', '010-1111-2222');

-- INSERT INTO CEO_USERS (C_ID, C_NAME, C_PSWORD, C_PH_NUM)
-- VALUES ('admin2', '곽채연', '1234567', '010-1131-2622');


-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P1','상의', 4000 , NULL , NULL , '1');
-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P2','하의', 4090 , NULL , NULL , '1');
-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P3','종합세탁', 5000 , NULL , NULL , '1');

-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P4','상의', 6000 , NULL , NULL , '2');
-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P5','하의', 9000 , NULL , NULL , '2');
-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P6','종합세탁', 5000 , NULL , NULL , '2');

-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P7','상의', 24000 , NULL , NULL , '3');
-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P8','하의', 14090 , NULL , NULL , '3');
-- INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_CREATE_DAY, PRODUCT_CORRECT_DAY, S_ID)
-- VALUES ('P9','종합세탁', 15000 , NULL , NULL , '3');

    
    
    
   
    
    
   
   
   
    
   




